name: google_photos_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth: ^1.4.1
  url_launcher: ^6.2.2
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  http: ^1.1.2
  logging: ^1.2.0
  image_picker: ^0.8.4+4 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bridge.jpg
    - assets/images/black.jpeg
